FROM oven/bun:1.2.17-alpine

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

COPY migrations ./migrations
COPY scripts ./scripts

CMD ["bun", "run", "migrate"]
