services:
  fgs:
    image: fgs_prod:latest
    container_name: fgs_prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - INTERNAL_API_ORIGIN=http://127.0.0.1:3000
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - TEST_DISCORD_STRING=${TEST_DISCORD_STRING}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - REFRESH_TOKEN_TTL_DAYS=${REFRESH_TOKEN_TTL_DAYS}
      - REFRESH_TOKEN_BYTES=${REFRESH_TOKEN_BYTES}
      - PASSWORD_SALT_ROUNDS=${PASSWORD_SALT_ROUNDS}
    networks: [fgs-net, dokploy-network]
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.fgsprod-http.rule=Host(`farooqigrammar.school`)"
      - "traefik.http.routers.fgsprod-http.entrypoints=web"
      - "traefik.http.routers.fgsprod-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.http.routers.fgsprod.rule=Host(`farooqigrammar.school`)"
      - "traefik.http.routers.fgsprod.entrypoints=websecure"
      - "traefik.http.routers.fgsprod.tls=true"
      - "traefik.http.routers.fgsprod.tls.certresolver=letsencrypt"

      - "traefik.http.middlewares.fgsprod-compress.compress=true"
      - "traefik.http.routers.fgsprod.middlewares=fgsprod-compress"

      - "traefik.http.services.fgsprod.loadbalancer.server.port=3000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      email_worker:
        condition: service_started

  email_worker:
    image: email_worker:latest
    container_name: email_worker
    restart: unless-stopped
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DESTINATION_EMAIL_ADDRESS=${DESTINATION_EMAIL_ADDRESS}
      - SENDER_EMAIL_ADDRESS=${SENDER_EMAIL_ADDRESS}
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_INTERVAL=${WORKER_INTERVAL}
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks: [fgs-net, dokploy-network]

  migrations:
    image: fgs_migrations:latest
    container_name: fgs_migrations
    restart: "no"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks: [fgs-net]

  db:
    image: postgres:15
    volumes:
      - fgs_prod_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    networks: [fgs-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  fgs-net:
  dokploy-network:
    external: true
volumes:
  fgs_prod_db:
