'use client';

import { cn } from '@/lib/utils';
import { type CSSProperties, type Ref, useId } from 'react';

// Inline version of public/fgs-logo.svg with each part addressable, so CSS can animate the
// pieces independently (keyframes live in globals.css under "FGS logo"). Static uses where
// nothing moves should keep using the /fgs-logo.svg file instead.
//
// Geometry is generated by .ignore/docs/artifacts/logo-svg/gen.js; keep the two in sync.

export type FgsLogoAnimation = 'none' | 'intro' | 'celebrate';

// Celebration droplets: [dx, dy, rotation, color, delay] in logo units from the figure.
const SPARKS = [
  [-285, -228, -40, '#00B3EE', 0],
  [285, -247, 40, '#FCCB21', 0.04],
  [-380, -19, -80, '#74CEF1', 0.08],
  [380, -38, 80, '#00B3EE', 0.02],
  [-171, -361, -20, '#FCCB21', 0.1],
  [190, -380, 20, '#74CEF1', 0.06],
  [-437, -171, -60, '#FCCB21', 0.12],
  [437, -190, 60, '#74CEF1', 0.1],
] as const;

export function FgsLogo({
  animation = 'none',
  label = 'Farooqi Grammar School logo',
  decorative = false,
  className,
  ref,
}: {
  animation?: FgsLogoAnimation;
  label?: string;
  /** Hide from assistive tech when the logo sits next to the school name. */
  decorative?: boolean;
  className?: string;
  ref?: Ref<SVGSVGElement>;
}) {
  // Gradient, clip and mask ids must be unique per instance or copies share the first one's.
  const id = `fgs-logo-${useId().replace(/[^\w-]/g, '')}`;
  const url = (name: string) => `url(#${id}-${name})`;

  return (
    <svg
      ref={ref}
      viewBox='26 56 540 520'
      xmlns='http://www.w3.org/2000/svg'
      className={cn('fgs-logo', animation !== 'none' && `fgs-logo--${animation}`, className)}
      {...(decorative ? { 'aria-hidden': true } : { role: 'img', 'aria-label': label })}
    >
      <defs>
        <radialGradient id={`${id}-sun`} gradientUnits='userSpaceOnUse' cx='282' cy='268' r='218'>
          <stop offset='0' stopColor='#FDE613' />
          <stop offset='.5' stopColor='#FCCB21' />
          <stop offset='1' stopColor='#FAB12C' />
        </radialGradient>
        <radialGradient id={`${id}-head`} cx='.5' cy='.5' r='.55' fx='.33' fy='.28'>
          <stop offset='0' stopColor='#F4FFFF' />
          <stop offset='.22' stopColor='#7FD6FA' />
          <stop offset='.6' stopColor='#16A8E6' />
          <stop offset='1' stopColor='#0384CC' />
        </radialGradient>
        <linearGradient id={`${id}-body`} gradientUnits='userSpaceOnUse' x1='0' y1='160' x2='0' y2='440'>
          <stop offset='0' stopColor='#0389D0' />
          <stop offset='.6' stopColor='#00B3EE' />
          <stop offset='1' stopColor='#0AC2F6' />
        </linearGradient>
        <linearGradient id={`${id}-arm`} gradientUnits='userSpaceOnUse' x1='185' y1='170' x2='275' y2='300'>
          <stop offset='0' stopColor='#05BDEE' />
          <stop offset='1' stopColor='#008ECF' />
        </linearGradient>
        {/* The sun rises from behind this horizon (just below its resting edge). */}
        <clipPath id={`${id}-horizon`}>
          <rect x='0' y='0' width='592' height='482' />
        </clipPath>
        {/* Two half-rings revealed from the bottom outwards sweep the arcs open. */}
        <mask id={`${id}-sweep`} maskUnits='userSpaceOnUse' x='0' y='0' width='592' height='581'>
          <g fill='none' stroke='#fff' strokeWidth='96' strokeDasharray='50 50'>
            <path className='fgs-logo__sweep' pathLength={50} d='M288,527A256,256 0 0 1 288,15' />
            <path className='fgs-logo__sweep' pathLength={50} d='M288,527A256,256 0 0 0 288,15' />
          </g>
        </mask>
      </defs>

      <circle className='fgs-logo__part fgs-logo__halo' cx='287.5' cy='270' r='222' fill='none' stroke='#FCCB21' strokeWidth='10' opacity='0' />
      <circle className='fgs-logo__part fgs-logo__halo2' cx='287.5' cy='270' r='222' fill='none' stroke='#74CEF1' strokeWidth='6' opacity='0' />

      <g mask={url('sweep')}>
        <path fill='#0390D4' d='M34.2,375.1A270.5,270.5 0 0 0 556,237.7A2.3,2.3 0 0 0 551.4,238.6A269.3,269.3 0 0 1 38.4,373.6A2.2,2.2 0 0 0 34.2,375.1Z' />
        <path fill='#74CEF1' d='M58.9,365.9A248,248 0 0 0 532.6,230.1A4.7,4.7 0 0 0 523.2,231.6A239.7,239.7 0 0 1 68.9,361.7A5.4,5.4 0 0 0 58.9,365.9Z' />
      </g>

      <g clipPath={url('horizon')}>
        <path className='fgs-logo__sun' fill={url('sun')} d='M81.9,350A217.4,217.4 0 1 1 493.1,350A226.5,226.5 0 0 1 81.9,350Z' />
      </g>

      <g className='fgs-logo__part fgs-logo__figure'>
        <path className='fgs-logo__part fgs-logo__arm' fill={url('arm')} d='M183,162C182,205 205,250 262,318L300,300L283,279C245,246 200,205 183,162Z' />
        <path fill={url('body')} d='M339,157C352,175 358,205 345,240C330,280 295,315 290,355C287,395 315,430 353,446C320,447 290,437 272,410C255,385 252,345 261,316L283,279C300,255 325,225 334,185C336,175 337,165 339,157Z' />
        <path className='fgs-logo__part fgs-logo__strand' fill={url('body')} d='M368,222C380,240 380,275 360,302C345,322 335,345 337,370C342,390 365,404 379,414C350,412 320,400 315,368C313,340 330,312 350,282C362,262 368,245 368,222Z' />
        <path className='fgs-logo__part fgs-logo__strand fgs-logo__strand--late' fill={url('body')} d='M390,271C397,285 395,305 380,325C368,342 362,358 372,374C378,384 386,390 395,395C375,393 360,385 356,365C353,345 365,325 378,308C386,297 390,285 390,271Z' />
        <path className='fgs-logo__part fgs-logo__drop' fill={url('body')} d='M400,316C404,330 413.3,343 413.3,360.5A16.3,16.3 0 1 1 380.7,360.5C380.7,348 393,335 400,316Z' />
        <circle className='fgs-logo__part fgs-logo__head' cx='275.5' cy='196' r='37.5' fill={url('head')} />
      </g>

      {animation === 'celebrate' ? (
        <g transform='translate(290,250)'>
          {SPARKS.map(([dx, dy, rotate, color, delay]) => (
            <g
              key={`${dx},${dy}`}
              className='fgs-logo__spark'
              style={{ '--dx': `${dx}px`, '--dy': `${dy}px`, '--r': `${rotate}deg`, '--d': `${delay}s` } as CSSProperties}
            >
              <path fill={color} d='M0,-18C3,-10 9,-5 9,3A9,9 0 1 1 -9,3C-9,-5 -3,-10 0,-18Z' />
            </g>
          ))}
        </g>
      ) : null}

      <g className='fgs-logo__part fgs-logo__book' fill='none' stroke='#347464' strokeWidth='7' strokeLinejoin='round' strokeLinecap='round'>
        <path fill='#fff' d='M212,467Q228,473 246,467T292,476Q320,461 338,467T372,467L428,546Q406,558 379,553.5T292,567Q232,549 205,553.5T156,546Z' />
        <path d='M167,531Q187,540 212,536T292,543.5Q347,532 372,536T417,531' />
        <path d='M292,476V543' />
      </g>
    </svg>
  );
}

/** Small open book whose pages flip on a loop; a branded busy indicator for buttons. */
export function FgsBookSpinner({ className }: { className?: string }) {
  const page = 'M15,5Q21,2 27,4L28,17Q21,15 15,18Z';
  return (
    <svg viewBox='0 0 30 22' aria-hidden className={cn('fgs-book-spinner', className)}>
      <g fill='#fff' stroke='currentColor' strokeWidth='1.6' strokeLinejoin='round'>
        <path d='M15,5Q9,2 3,4L2,17Q9,15 15,18Z' />
        <path d={page} />
        <path className='fgs-book-spinner__page' d={page} fill='#fff8e1' />
        <path className='fgs-book-spinner__page fgs-book-spinner__page--late' d={page} fill='#fff8e1' />
      </g>
    </svg>
  );
}
